---
title: "watershedR"
format: html
editor: visual
---

Concentration calculation of Potassium, Nitrate, Magnesium, Calcium and Ammonium in four watersheds of Puerto Rico.

## Load packages

```{r}
library(tidyverse)
library(janitor)
library(zoo)
```

## Read and clean data

```{r}
MPR <- read_csv(here::here("data", "RioMameyesPuenteRoto.csv"),
                na = c(" ", "NA")) %>%
clean_names() #clean data

QB1 <- read_csv(here::here("data", "QuebradaCuenca1-Bisley.csv"),
                na = c(" ", "NA")) %>%
  clean_names() #clean data

QB2 <- read_csv(here::here("data", "QuebradaCuenca2-Bisley.csv"),
                na = c(" ", "NA")) %>%
  clean_names() #clean data

QB3 <- read_csv(here::here("data", "QuebradaCuenca3-Bisley.csv"),
                na = c(" ", "NA")) %>%
  clean_names() #clean data
```

## Join data sets

```{r}
df_join1 <- full_join(MPR, QB1)

df_join2 <- full_join(QB2, QB3)

df_join <- full_join(df_join1, df_join2)

df_join_selected <- df_join %>%
  select("sample_id", "sample_date", "no3_n", "k", "mg", "ca", "nh4_n")

df_join_working <- df_join_selected %>%
  mutate(year = year(sample_date))
```

```{r}
roll_mean <- df_join_working %>%
  group_by(sample_id) %>%
  mutate(rollmean_no3 = rollmean(x = no3_n, k = 9, fill = NA, align = "left")) %>%
  ungroup() # optional code
```

```{r}
#moving_average <- function(focal_date, dates, conc, win_size_wks) {
  # Which dates are in the window?
  #is_in_window <- (dates > focal_date - (win_size_wks / 2) * 7) &
    #(dates < focal_date + (win_size_wks / 2) * 7)
  # Find the associated concentrations
  #window_conc <- conc[is_in_window]
  # Calculate the mean
  #result <- mean(window_conc)

```
